# Day 1 — NumPy Basics for Machine Learning
### Machine Learning Roadmap — Week 1
### Author: N Manish Kumar

## 1. Introduction

In this notebook , I will :
- Creaating Arrays
- Array Shape and Dimensions
- Indexing and Slicing
- Vector and Matrix Operationss
- Broadcasting
- Statistics and Aggregations
- Randomness
- Mini ML Tasks
This builds the foundation for understanding ML algorithms like Linear Regression and Neural Networks.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 2. Creating Arrays

In [2]:
# A python List
list_1 = [1, 2, 3, 4, 5]
#This creates a 1-D array containing the same elements as the list 
np_arr_1 = np.array(list_1) 

#Create multidimensional list
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create NumPy multidimensional (2 axis) array without defining type
np_m_arr_1 = np.array(m_list_1)

#You can also create arrays by defining the start value,
#Stop value (upto but not include stop) and step amount
np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# You can Create a 3 item arrays of Zeros
np.zeros(3)

array([0., 0., 0.])

In [4]:
# Create random 5 value 1D array from 10 to 50
np.random.randint(10, 50, 5)

array([36, 14, 47, 47, 32], dtype=int32)

## 3.Array Shape and Dimensions

In [5]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# Shape Attribute will display a tuple of integers that indicate the number of elements stored along each dimension of the array
array_example.shape

(3, 2, 4)

In [6]:
# ndim will tell you the number of axes, or dimensions, of the array.
array_example.ndim

3

In [7]:
#Reshape will give a new shape to an array without changing the data.But only if it has the same number of elements as the original array
array_example.reshape(2,3,4)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3]],

       [[4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7]]])

## 4.Indexing and Slicing

In [8]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
data[-2:]

2
[1 2]
[2 3]


array([2, 3])

## 5.Broadcasting
Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1.

In [9]:
ata = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2, 4.8])

## 6.Vector and Matrix Operations

In [10]:
# Vector Operations
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('Dot product =', np.dot(a, b))

a + b = [ 3  7 11]
a - b = [1 1 1]
a * b = [ 2 12 30]
Dot product = 44


In [11]:
# Matrix Operations
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(M.shape)
M.T

(3, 3)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
print('M + 2 =\n', M + 2)
print('M * 2 =\n', M * 2)

M + 2 =
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
M * 2 =
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [13]:
# Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A @ B

array([[19, 22],
       [43, 50]])

## 7.Statistics and Aggregates

In [14]:
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.std())

3
1
6
2.0
0.816496580927726


In [15]:
# Aggregate Functions
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())
print(a.min(axis=0))

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


## 8.Randomness

In [16]:
print(np.random.rand(10))

#It gives a different value every run.
np.random.randn()

#It fixes the randomness so you get the same random numbers every time you run
np.random.seed()

[0.82449747 0.55396721 0.33295856 0.00869207 0.1044976  0.86578127
 0.26394362 0.80579113 0.77519572 0.05348921]


## 9.Mini ML Tasks


In [17]:
# Example dataset
X = np.array([
    [50, 30],
    [60, 35],
    [70, 40],
    [80, 45]
])   # Features: [weight, age]

y = np.array([0, 0, 1, 1])   # Labels

In [18]:
# feature Normalization
mean = X.mean(axis=0)
std = X.std(axis=0)

X_norm = (X - mean) / std
print(X_norm)

[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


In [19]:
# Computing Euclidean Distance
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))
d = euclidean_distance(X_norm[0], X_norm[1])
print(d)

1.2649110640673518


In [20]:
# Implementing Prediction Step
w = np.array([0.5, -0.3])
b = 0.1
y_pred = X_norm@w +b
print(y_pred)

[-0.16832816  0.01055728  0.18944272  0.36832816]


In [21]:
# Loss Function (MSE)
mse=np.mean((y-y_pred)**2)
mse

np.float64(0.2711145618000168)

In [22]:
#Sigmoid Function
def sigmoid(z):
    return 1/1+(np.exp(-z))
y_probability=sigmoid(y_pred)
print(y_probability)

[2.18332486 1.98949825 1.82742011 1.6918901 ]


## 10. Summary
- Learned Basic Numpy implementation
- Practiced Numpy Operations
- Built Decent ML math foundations